/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "#FAFAFA",
        surface: "#F0F2F5",
        "surface-2": "#E8EAED",
        border: { DEFAULT: "#DDE1E7" },
        text: { DEFAULT: "#111827", 2: "#4B5563", 3: "#9CA3AF" },
        accent: {
          DEFAULT: "#C8410A",
          bg: "#FEF3EE",
          hover: "#A33508",
          foreground: "#ffffff",
        },
        success: { DEFAULT: "#1A7A4A", bg: "#ECFBF1" },
        danger: { DEFAULT: "#C8190A", bg: "#FEF2F2" },
        /* shadcn compat */
        primary: { DEFAULT: "#C8410A", foreground: "#ffffff" },
        secondary: { DEFAULT: "#F0F2F5", foreground: "#111827" },
        muted: { DEFAULT: "#F0F2F5", foreground: "#4B5563" },
        card: { DEFAULT: "#FFFFFF", foreground: "#111827" },
        input: "#DDE1E7",
        ring: "#C8410A",
        background: "#FAFAFA",
        foreground: "#111827",
        destructive: { DEFAULT: "#C8190A", foreground: "#ffffff" },
        popover: { DEFAULT: "#FFFFFF", foreground: "#111827" },
      },
      fontFamily: {
        sans: ["DM Sans", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        xs: ["12px", "16px"],
        sm: ["13px", "18px"],
        base: ["15px", "22px"],
        lg: ["17px", "24px"],
        xl: ["20px", "28px"],
        "2xl": ["24px", "32px"],
        "3xl": ["30px", "36px"],
        "4xl": ["36px", "40px"],
        "5xl": ["48px", "52px"],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "6px",
        md: "6px",
        lg: "8px",
        xl: "10px",
        "2xl": "12px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0,0,0,0.06)",
        DEFAULT: "0 1px 3px rgba(0,0,0,0.08), 0 1px 2px rgba(0,0,0,0.06)",
        md: "0 2px 8px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.06)",
        none: "none",
      },
      letterSpacing: {
        tight: "-0.02em",
        normal: "0",
        wide: "0.04em",
        wider: "0.08em",
      },
    },
  },
  plugins: [],
}
